name: Test
on:
  push:
    branches:
      - main
  schedule:
    - cron: 30 1 * * *
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
jobs:
  build:
    name: Examples
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install the latest Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Install the latest Node
      - uses: actions/setup-node@v3

      - run: |
          make test
